// <auto-generated />
namespace Pricelist_Portal_Khantil_Anton_43650.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HeadphoneClumnLengthChanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HeadphoneClumnLengthChanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201805121332095_HeadphoneClumnLengthChanged"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
